# Generated by Django 4.1 on 2023-05-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, default='NEW', max_length=32, null=True)),
            ],
        ),
    ]
